### ISSUE TITLE
npm i - failed on macos

### ISSUE THREAD

**Issue by i001962** [pranah/prana#1]
What version of node did you successfully build this project on? I'm failing with Error: `gyp` which seems like a node version issue. 

I enjoyed the video and voted for you in my top 5. Nice work.

**Comment by RichuAK** [comment]
Hey, we'd built this on node v12.18.3

We ran `npm i` on mac, seems to work fine. There were a few warnings though. 

Thanks for your vote! We really want to pursue this further.

**Comment by RichuAK** [comment]
Were you able to install and run it successfully?

**Comment by i001962** [comment]
Sadly, I had to move on. Sounds like a local issue. Feel free to close.
